name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.18.0  # Asegúrate de especificar la versión de Node.js que necesitas
    
    - name: Install dependencies
      run: npm install

    - name: Lint with ESLint
      run: npx eslint .
    
    - name: Test with Mocha
      run: npx mocha
