# Use a Node.js base image
FROM node:14

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose the port your application is listening on (if applicable)
# EXPOSE 3000
#EXPOSE 1883
# Run the application
CMD [ "node", "mqtt.js" ]
